namespace DuplicateFinderPro.App.Localization;

/// <summary>
/// The full translation table. Every UI string lives here keyed by a stable id,
/// with a Persian (fa) and English (en) value. Adding a language means adding
/// one more dictionary and registering it in <see cref="Localization"/>.
/// </summary>
internal static class Strings
{
    public static readonly IReadOnlyDictionary<string, string> Fa = new Dictionary<string, string>
    {
        ["App.Title"] = "یابنده‌ی فایل‌های تکراری حرفه‌ای",
        ["App.Subtitle"] = "پیدا کردن فایل‌های تکراری بر اساس محتوا، نام و شباهت تصویری",

        ["Menu.Language"] = "زبان",
        ["Menu.Theme"] = "پوسته",
        ["Theme.Light"] = "روشن",
        ["Theme.Dark"] = "تیره",
        ["Lang.Persian"] = "فارسی",
        ["Lang.English"] = "English",

        ["Config.Header"] = "تنظیمات پویش",
        ["Config.Folders"] = "پوشه‌ها",
        ["Config.AddFolder"] = "افزودن پوشه",
        ["Config.RemoveFolder"] = "حذف",
        ["Config.DropHint"] = "پوشه‌ها را اینجا رها کنید یا «افزودن پوشه» را بزنید",
        ["Config.Methods"] = "روش‌های تشخیص",
        ["Config.Filters"] = "فیلترها",
        ["Config.Advanced"] = "پیشرفته",
        ["Config.Recursive"] = "جست‌وجو در زیرپوشه‌ها",
        ["Config.IncludeHidden"] = "شامل فایل‌های مخفی/سیستمی",
        ["Config.MinSize"] = "کمینه اندازه (کیلوبایت)",
        ["Config.MaxSize"] = "بیشینه اندازه (کیلوبایت، ۰=نامحدود)",
        ["Config.IncludeExt"] = "فقط این پسوندها (با کاما)",
        ["Config.ExcludeExt"] = "نادیده گرفتن پسوندها (با کاما)",
        ["Config.NameThreshold"] = "آستانه شباهت نام",
        ["Config.PerceptualThreshold"] = "آستانه شباهت تصویری (۰ تا ۶۴)",
        ["Config.VideoSamples"] = "تعداد فریم نمونه از هر ویدیو",
        ["Config.Ffmpeg"] = "مسیر ffmpeg (اختیاری)",

        ["Method.ExactContent"] = "محتوای دقیقاً یکسان (Hash)",
        ["Method.ExactContent.Desc"] = "فایل‌های بایت‌به‌بایت یکسان، حتی با نام متفاوت",
        ["Method.NameSimilarity"] = "شباهت نام فایل",
        ["Method.NameSimilarity.Desc"] = "نام‌های شبیه مثل Movie و Movie (1)",
        ["Method.PerceptualImage"] = "تصاویر هم‌شکل",
        ["Method.PerceptualImage.Desc"] = "عکس یکسان با فرمت یا کیفیت متفاوت",
        ["Method.PerceptualVideo"] = "ویدیوهای هم‌شکل (ffmpeg)",
        ["Method.PerceptualVideo.Desc"] = "یک فیلم با نام/کیفیت متفاوت",

        ["Action.Scan"] = "شروع پویش",
        ["Action.Cancel"] = "لغو",
        ["Action.Export"] = "خروجی گزارش",
        ["Action.ExportCsv"] = "خروجی CSV",
        ["Action.ExportJson"] = "خروجی JSON",
        ["Action.Recycle"] = "انتقال به سطل بازیافت",
        ["Action.DeletePermanently"] = "حذف دائمی",
        ["Action.MoveTo"] = "انتقال به پوشه…",
        ["Action.OpenFolder"] = "باز کردن محل فایل",
        ["Action.SelectByRule"] = "انتخاب خودکار",
        ["Action.ClearSelection"] = "پاک کردن انتخاب",
        ["Action.ExpandAll"] = "باز کردن همه",
        ["Action.CollapseAll"] = "بستن همه",

        ["Keep.Rule"] = "نگه‌داشتن بر اساس",
        ["Keep.Newest"] = "جدیدترین",
        ["Keep.Oldest"] = "قدیمی‌ترین",
        ["Keep.Largest"] = "بزرگ‌ترین",
        ["Keep.Smallest"] = "کوچک‌ترین",
        ["Keep.ShortestPath"] = "کوتاه‌ترین مسیر",
        ["Keep.CleanestName"] = "تمیزترین نام",

        ["Results.Header"] = "نتایج",
        ["Results.NoResults"] = "هنوز پویشی انجام نشده است",
        ["Results.NoDuplicates"] = "هیچ فایل تکراری‌ای پیدا نشد 🎉",
        ["Results.Group"] = "گروه",
        ["Results.FilesScanned"] = "فایل‌های بررسی‌شده",
        ["Results.Groups"] = "گروه‌های تکراری",
        ["Results.RedundantFiles"] = "فایل‌های اضافی",
        ["Results.Reclaimable"] = "فضای قابل آزادسازی",
        ["Results.Elapsed"] = "زمان",
        ["Results.Warnings"] = "هشدارها",
        ["Results.Selected"] = "انتخاب‌شده",

        ["Grid.Keep"] = "نگه‌داری",
        ["Grid.File"] = "نام فایل",
        ["Grid.Folder"] = "پوشه",
        ["Grid.Size"] = "اندازه",
        ["Grid.Modified"] = "آخرین تغییر",

        ["Status.Idle"] = "آماده",
        ["Status.Enumerating"] = "در حال فهرست‌برداری فایل‌ها…",
        ["Status.HashingContent"] = "در حال محاسبه هش محتوا…",
        ["Status.MatchingNames"] = "در حال تطبیق نام‌ها…",
        ["Status.HashingPerceptual"] = "در حال تحلیل تصاویر…",
        ["Status.SamplingVideo"] = "در حال نمونه‌برداری از ویدیوها…",
        ["Status.Finalizing"] = "در حال جمع‌بندی…",
        ["Status.Completed"] = "پویش کامل شد",
        ["Status.Cancelled"] = "پویش لغو شد",
        ["Status.Faulted"] = "خطا در پویش",

        ["Msg.NeedFolder"] = "لطفاً حداقل یک پوشه اضافه کنید.",
        ["Msg.NeedMethod"] = "لطفاً حداقل یک روش تشخیص را انتخاب کنید.",
        ["Msg.NothingSelected"] = "هیچ فایلی انتخاب نشده است.",
        ["Msg.ConfirmRecycle"] = "‏{0} فایل به سطل بازیافت منتقل شود؟",
        ["Msg.ConfirmDelete"] = "‏{0} فایل برای همیشه حذف شود؟ این عمل قابل بازگشت نیست!",
        ["Msg.ActionDone"] = "‏{0} فایل پردازش شد، {1} آزاد شد.",
        ["Msg.ActionErrors"] = "‏{0} فایل با خطا مواجه شد.",
        ["Msg.ExportDone"] = "گزارش ذخیره شد.",

        ["Common.Ok"] = "تأیید",
        ["Common.Cancel"] = "انصراف",
        ["Common.Yes"] = "بله",
        ["Common.No"] = "خیر",
        ["Common.Confirm"] = "تأیید عملیات",
        ["Common.Warning"] = "هشدار",
    };

    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["App.Title"] = "Duplicate Finder Pro",
        ["App.Subtitle"] = "Find duplicate files by content, name and visual similarity",

        ["Menu.Language"] = "Language",
        ["Menu.Theme"] = "Theme",
        ["Theme.Light"] = "Light",
        ["Theme.Dark"] = "Dark",
        ["Lang.Persian"] = "فارسی",
        ["Lang.English"] = "English",

        ["Config.Header"] = "Scan Settings",
        ["Config.Folders"] = "Folders",
        ["Config.AddFolder"] = "Add folder",
        ["Config.RemoveFolder"] = "Remove",
        ["Config.DropHint"] = "Drop folders here or click “Add folder”",
        ["Config.Methods"] = "Detection methods",
        ["Config.Filters"] = "Filters",
        ["Config.Advanced"] = "Advanced",
        ["Config.Recursive"] = "Search sub-folders",
        ["Config.IncludeHidden"] = "Include hidden/system files",
        ["Config.MinSize"] = "Minimum size (KB)",
        ["Config.MaxSize"] = "Maximum size (KB, 0 = unlimited)",
        ["Config.IncludeExt"] = "Only these extensions (comma separated)",
        ["Config.ExcludeExt"] = "Ignore extensions (comma separated)",
        ["Config.NameThreshold"] = "Name similarity threshold",
        ["Config.PerceptualThreshold"] = "Image similarity threshold (0–64)",
        ["Config.VideoSamples"] = "Sample frames per video",
        ["Config.Ffmpeg"] = "ffmpeg path (optional)",

        ["Method.ExactContent"] = "Exact content (hash)",
        ["Method.ExactContent.Desc"] = "Byte-for-byte identical files, even with different names",
        ["Method.NameSimilarity"] = "File name similarity",
        ["Method.NameSimilarity.Desc"] = "Similar names like Movie and Movie (1)",
        ["Method.PerceptualImage"] = "Look-alike images",
        ["Method.PerceptualImage.Desc"] = "Same picture in a different format or quality",
        ["Method.PerceptualVideo"] = "Look-alike videos (ffmpeg)",
        ["Method.PerceptualVideo.Desc"] = "The same movie under a different name/quality",

        ["Action.Scan"] = "Start scan",
        ["Action.Cancel"] = "Cancel",
        ["Action.Export"] = "Export report",
        ["Action.ExportCsv"] = "Export CSV",
        ["Action.ExportJson"] = "Export JSON",
        ["Action.Recycle"] = "Move to Recycle Bin",
        ["Action.DeletePermanently"] = "Delete permanently",
        ["Action.MoveTo"] = "Move to folder…",
        ["Action.OpenFolder"] = "Open file location",
        ["Action.SelectByRule"] = "Auto-select",
        ["Action.ClearSelection"] = "Clear selection",
        ["Action.ExpandAll"] = "Expand all",
        ["Action.CollapseAll"] = "Collapse all",

        ["Keep.Rule"] = "Keep by",
        ["Keep.Newest"] = "Newest",
        ["Keep.Oldest"] = "Oldest",
        ["Keep.Largest"] = "Largest",
        ["Keep.Smallest"] = "Smallest",
        ["Keep.ShortestPath"] = "Shortest path",
        ["Keep.CleanestName"] = "Cleanest name",

        ["Results.Header"] = "Results",
        ["Results.NoResults"] = "No scan has been run yet",
        ["Results.NoDuplicates"] = "No duplicate files found 🎉",
        ["Results.Group"] = "Group",
        ["Results.FilesScanned"] = "Files scanned",
        ["Results.Groups"] = "Duplicate groups",
        ["Results.RedundantFiles"] = "Redundant files",
        ["Results.Reclaimable"] = "Reclaimable space",
        ["Results.Elapsed"] = "Elapsed",
        ["Results.Warnings"] = "Warnings",
        ["Results.Selected"] = "Selected",

        ["Grid.Keep"] = "Keep",
        ["Grid.File"] = "File name",
        ["Grid.Folder"] = "Folder",
        ["Grid.Size"] = "Size",
        ["Grid.Modified"] = "Last modified",

        ["Status.Idle"] = "Ready",
        ["Status.Enumerating"] = "Enumerating files…",
        ["Status.HashingContent"] = "Hashing file content…",
        ["Status.MatchingNames"] = "Matching names…",
        ["Status.HashingPerceptual"] = "Analyzing images…",
        ["Status.SamplingVideo"] = "Sampling videos…",
        ["Status.Finalizing"] = "Finalizing…",
        ["Status.Completed"] = "Scan complete",
        ["Status.Cancelled"] = "Scan cancelled",
        ["Status.Faulted"] = "Scan failed",

        ["Msg.NeedFolder"] = "Please add at least one folder.",
        ["Msg.NeedMethod"] = "Please select at least one detection method.",
        ["Msg.NothingSelected"] = "No files are selected.",
        ["Msg.ConfirmRecycle"] = "Move {0} file(s) to the Recycle Bin?",
        ["Msg.ConfirmDelete"] = "Permanently delete {0} file(s)? This cannot be undone!",
        ["Msg.ActionDone"] = "Processed {0} file(s), freed {1}.",
        ["Msg.ActionErrors"] = "{0} file(s) failed.",
        ["Msg.ExportDone"] = "Report saved.",

        ["Common.Ok"] = "OK",
        ["Common.Cancel"] = "Cancel",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Confirm"] = "Confirm action",
        ["Common.Warning"] = "Warning",
    };
}
