namespace DuplicateFinderPro.App.Localization;

/// <summary>
/// The full translation table. Every UI string lives here keyed by a stable id,
/// with a Persian (fa) and English (en) value. Adding a language means adding
/// one more dictionary and registering it in <see cref="Localization"/>.
/// </summary>
internal static class Strings
{
    public static readonly IReadOnlyDictionary<string, string> Fa = new Dictionary<string, string>
    {
        ["App.Title"] = "یابنده‌ی فایل‌های تکراری حرفه‌ای",
        ["App.Subtitle"] = "پیدا کردن فایل‌های تکراری بر اساس محتوا، نام و شباهت تصویری",

        ["Menu.Language"] = "زبان",
        ["Menu.Theme"] = "پوسته",
        ["Theme.Light"] = "روشن",
        ["Theme.Dark"] = "تیره",
        ["Lang.Persian"] = "فارسی",
        ["Lang.English"] = "English",

        ["Config.Header"] = "تنظیمات پویش",
        ["Config.Folders"] = "پوشه‌ها",
        ["Config.AddFolder"] = "افزودن پوشه",
        ["Config.RemoveFolder"] = "حذف",
        ["Config.DropHint"] = "پوشه‌ها را اینجا رها کنید یا «افزودن پوشه» را بزنید",
        ["Config.Methods"] = "روش‌های تشخیص",
        ["Config.Filters"] = "فیلترها",
        ["Config.Advanced"] = "پیشرفته",
        ["Config.Recursive"] = "جست‌وجو در زیرپوشه‌ها",
        ["Config.IncludeHidden"] = "شامل فایل‌های مخفی/سیستمی",
        ["Config.MinSize"] = "کمینه اندازه (کیلوبایت)",
        ["Config.MaxSize"] = "بیشینه اندازه (کیلوبایت، ۰=نامحدود)",
        ["Config.IncludeExt"] = "فقط این پسوندها (با کاما)",
        ["Config.ExcludeExt"] = "نادیده گرفتن پسوندها (با کاما)",
        ["Config.FileTypes"] = "نوع فایل‌ها برای اسکن",
        ["Config.FileTypesHint"] = "خالی = همه‌ی فایل‌ها. با انتخاب، فقط همین نوع‌ها جست‌وجو می‌شوند (سراغ فایل‌های اجرایی/سیستمی نمی‌رود).",
        ["Cat.Images"] = "عکس",
        ["Cat.Videos"] = "ویدیو",
        ["Cat.Audio"] = "صوت",
        ["Cat.Documents"] = "سند",
        ["Cat.Archives"] = "آرشیو",
        ["Config.NameThreshold"] = "آستانه شباهت نام",
        ["Config.PerceptualThreshold"] = "آستانه شباهت تصویری (۰ تا ۶۴)",
        ["Config.VideoSamples"] = "تعداد فریم نمونه از هر ویدیو",
        ["Config.VideoIntroSkip"] = "پرش از ابتدا (٪)",
        ["Config.VideoOutroSkip"] = "پرش از انتها (٪)",
        ["Config.Gentle"] = "حالت کم‌مصرف (فشار کمتر روی سیستم)",
        ["Config.Ffmpeg"] = "مسیر ffmpeg (اختیاری)",

        ["Config.ResourceUsage"] = "مصرف منابع",
        ["Res.Maximum"] = "حداکثر",
        ["Res.Maximum.Desc"] = "استفاده از تمام هسته‌ها — سریع‌ترین ولی سیستم مشغول می‌شود",
        ["Res.Balanced"] = "متوسط",
        ["Res.Balanced.Desc"] = "نیمی از هسته‌ها — پیش‌فرض متعادل و روان",
        ["Res.Light"] = "کم",
        ["Res.Light.Desc"] = "تک‌رشته و کم‌اولویت — ملایم روی هارد (مناسب HDD)",

        ["Config.ExcludedFolders"] = "پوشه‌های نادیده‌گرفته‌شده",
        ["Config.AddExcluded"] = "افزودن پوشه‌ی استثنا",
        ["Config.ExcludedHint"] = "این زیرپوشه‌ها هنگام سرچ نادیده گرفته می‌شوند",

        ["Scan.Title"] = "در حال اسکن…",
        ["Scan.FilesFound"] = "فایل پیداشده",
        ["Scan.Processed"] = "پردازش‌شده",
        ["Scan.Duplicates"] = "تکراری پیداشده",
        ["Scan.Elapsed"] = "زمان سپری‌شده",
        ["Scan.Location"] = "موقعیت فعلی",
        ["Scan.Phase"] = "مرحله",
        ["Scan.Remaining"] = "زمان باقی‌مانده",
        ["Scan.CurrentFile"] = "فایل در حال بررسی",
        ["Scan.FilesUnit"] = "فایل",
        ["Scan.ReadingFile"] = "در حال خواندن این فایل",

        ["Explain.Enumerating"] = "در حال فهرست‌کردن همه‌ی فایل‌های داخل پوشه‌ها و زیرپوشه‌ها.",
        ["Explain.QuickScan"] = "غربال سریع: فقط بخش کوچکی از هر فایلِ هم‌اندازه خوانده می‌شود تا بیشترشان بدون خواندن کامل کنار بروند.",
        ["Explain.HashingContent"] = "خواندن کاملِ فایل‌های کاندید و ساخت امضای یکتا (SHA-256) برای تأیید تکراریِ بایت‌به‌بایت. سنگین‌ترین مرحله است.",
        ["Explain.MatchingNames"] = "مقایسه‌ی نام فایل‌ها برای یافتن کپی‌های تغییرنام‌یافته.",
        ["Explain.HashingPerceptual"] = "ساخت اثرانگشت تصویری هر عکس برای یافتن عکس‌های هم‌شکل.",
        ["Explain.SamplingVideo"] = "نمونه‌برداری از فریم‌های هر ویدیو برای یافتن فیلم‌های یکسان.",
        ["Explain.AnalyzingPhotos"] = "بررسی تار/تاریک/اسکرین‌شات بودن هر عکس.",
        ["Explain.Finalizing"] = "جمع‌بندی و گروه‌بندی نتایج.",

        ["Adv.NameSection"] = "تطبیق نام فایل",
        ["Adv.ImageSection"] = "تصاویر",
        ["Adv.VideoSection"] = "ویدیوها",
        ["Adv.NameDesc"] = "نام‌ها نرمال‌سازی و با «فاصله‌ی ویرایشی» مقایسه می‌شوند. آستانه‌ی بالاتر = سخت‌گیرتر.",
        ["Adv.ImageDesc"] = "اثرانگشت ادراکی (dHash) عکس‌ها مقایسه می‌شود؛ ریسایز، فشرده‌سازی و تغییر فرمت را می‌پوشاند. عدد کمتر = سخت‌گیرتر.",
        ["Adv.VideoDesc"] = "از سراسر مدت فیلم چند فریم نمونه گرفته می‌شود (نه فقط ابتدا) تا فیلم‌هایی با تیتراژ یکسان اشتباه ادغام نشوند. فریم بیشتر = دقیق‌تر ولی کندتر.",
        ["Adv.GentleDesc"] = "تحلیل رسانه با اولویت پایین و هم‌زمانی محدود اجرا می‌شود تا سیستم کند نشود.",
        ["Adv.EnableHint"] = "برای فعال شدن، این روش را در «روش‌های تشخیص» تیک بزنید",
        ["Adv.NamePro"] = "خوبی: سریع است و کپی‌های تغییرنام‌یافته را پیدا می‌کند.",
        ["Adv.NameCon"] = "بدی: ممکن است فایل‌های متفاوت با نام مشابه را در یک گروه بگذارد.",
        ["Adv.ImagePro"] = "خوبی: عکس یکسان با فرمت/اندازه/کیفیت متفاوت را تشخیص می‌دهد.",
        ["Adv.ImageCon"] = "بدی: کمی کندتر؛ با آستانه‌ی شل ممکن است عکس‌های فقط «شبیه» را هم یکی بشمارد.",
        ["Adv.VideoPro"] = "خوبی: یک فیلم را با نام/کیفیت/فرمت متفاوت هم پیدا می‌کند.",
        ["Adv.VideoCon"] = "بدی: به ffmpeg نیاز دارد و پردازشش زمان‌بر و سنگین است.",
        ["Adv.VideoSampling"] = "از نقاط تصادفی در سراسر فیلم (ابتدا، وسط و انتها) نمونه گرفته می‌شود؛ هر بار پویش نقاط متفاوت اما برای نسخه‌های یک فیلم یکسان است.",

        ["Action.DownloadFfmpeg"] = "دانلود خودکار ffmpeg",
        ["Ffmpeg.Ready"] = "‏ffmpeg آماده است ✓",
        ["Ffmpeg.Missing"] = "‏ffmpeg یافت نشد — برای تشخیص ویدیو لازم است",
        ["Ffmpeg.Downloading"] = "در حال دانلود ffmpeg…",
        ["Ffmpeg.Done"] = "‏ffmpeg با موفقیت نصب شد ✓",
        ["Ffmpeg.Failed"] = "دانلود ffmpeg ناموفق بود",
        ["Ffmpeg.Redownload"] = "دانلود مجدد",

        ["Status.AnalyzingPhotos"] = "در حال تحلیل کیفیت عکس‌ها…",

        ["Tab.Duplicates"] = "فایل‌های تکراری",
        ["Tab.PhotoCleanup"] = "پاک‌سازی عکس",
        ["Tab.Statistics"] = "آمار",

        ["Method.PhotoQuality"] = "تحلیل کیفیت عکس (پاک‌سازی گالری)",
        ["Method.PhotoQuality.Desc"] = "پیدا کردن عکس‌های تار، تاریک، کم‌کیفیت و اسکرین‌شات",

        ["Photo.Blurry"] = "تار",
        ["Photo.Dark"] = "تاریک",
        ["Photo.Overexposed"] = "سوخته",
        ["Photo.LowResolution"] = "کیفیت پایین",
        ["Photo.Screenshot"] = "اسکرین‌شات",
        ["Photo.Good"] = "سالم",
        ["Photo.ShowOnlyFlagged"] = "فقط عکس‌های مشکل‌دار",
        ["Photo.SelectFlagged"] = "انتخاب همه‌ی مشکل‌دارها",
        ["Photo.NoPhotos"] = "هنوز تحلیلی انجام نشده — گزینه «تحلیل کیفیت عکس» را تیک بزنید و اسکن کنید",
        ["Photo.Analyzed"] = "عکس تحلیل‌شده",
        ["Photo.Flagged"] = "مشکل‌دار",

        ["Grid.Preview"] = "پیش‌نمایش",
        ["Grid.Score"] = "امتیاز",
        ["Grid.Issues"] = "مشکلات",
        ["Grid.Resolution"] = "ابعاد",

        ["Stat.Type.Images"] = "عکس‌ها",
        ["Stat.Type.Videos"] = "ویدیوها",
        ["Stat.Type.Other"] = "سایر",
        ["Stat.ByType"] = "حجم بر اساس نوع فایل",
        ["Stat.ByMethod"] = "فضای قابل آزادسازی بر اساس روش",
        ["Stat.PhotoQuality"] = "وضعیت کیفیت عکس‌ها",
        ["Stat.TopGroups"] = "بزرگ‌ترین گروه‌های تکراری",
        ["Stat.Overview"] = "نمای کلی",
        ["Stat.BytesScanned"] = "حجم بررسی‌شده",
        ["Stat.NoStats"] = "بعد از اسکن، آمار اینجا نمایش داده می‌شود",

        ["Adv.PhotoSection"] = "کیفیت عکس",
        ["Adv.PhotoDesc"] = "تیزی (واریانس لاپلاسین)، روشنایی و ابعاد سنجیده می‌شود تا عکس‌های تار/تاریک/اسکرین‌شات مشخص شوند.",
        ["Adv.PhotoPro"] = "خوبی: برای پاک‌سازی سریع گالری گوشی عالی است.",
        ["Adv.PhotoCon"] = "بدی: قضاوت سلیقه‌ای است؛ قبل از حذف حتماً نگاه کن.",
        ["Config.BlurSensitivity"] = "حساسیت تشخیص تاری (بیشتر = سخت‌گیرتر)",

        ["Method.ExactContent"] = "محتوای دقیقاً یکسان (Hash)",
        ["Method.ExactContent.Desc"] = "فایل‌های بایت‌به‌بایت یکسان، حتی با نام متفاوت",
        ["Method.NameSimilarity"] = "شباهت نام فایل",
        ["Method.NameSimilarity.Desc"] = "نام‌های شبیه مثل Movie و Movie (1)",
        ["Method.PerceptualImage"] = "تصاویر هم‌شکل",
        ["Method.PerceptualImage.Desc"] = "عکس یکسان با فرمت یا کیفیت متفاوت",
        ["Method.PerceptualVideo"] = "ویدیوهای هم‌شکل (ffmpeg)",
        ["Method.PerceptualVideo.Desc"] = "یک فیلم با نام/کیفیت متفاوت",

        ["Action.Scan"] = "شروع پویش",
        ["Action.Cancel"] = "لغو",
        ["Action.Export"] = "خروجی گزارش",
        ["Action.ExportCsv"] = "خروجی CSV",
        ["Action.ExportJson"] = "خروجی JSON",
        ["Action.Recycle"] = "انتقال به سطل بازیافت",
        ["Action.DeletePermanently"] = "حذف دائمی",
        ["Action.MoveTo"] = "انتقال به پوشه…",
        ["Action.OpenFolder"] = "باز کردن محل فایل",
        ["Action.SelectByRule"] = "انتخاب خودکار",
        ["Action.ClearSelection"] = "پاک کردن انتخاب",
        ["Action.ExpandAll"] = "باز کردن همه",
        ["Action.CollapseAll"] = "بستن همه",
        ["Action.Search"] = "جست‌وجو در نتایج…",
        ["Action.Import"] = "وارد کردن نتایج",
        ["Action.SaveSession"] = "ذخیره نتایج",

        ["Filter.Title"] = "فیلتر و دسته‌بندی",
        ["Filter.Reasons"] = "بر اساس دلیل تطابق",
        ["Filter.MatchAll"] = "همه‌ی موارد انتخاب‌شده باشند",
        ["Filter.MinSimilarity"] = "حداقل شباهت",
        ["Filter.MinCount"] = "حداقل تعداد فایل در گروه",
        ["Filter.Reset"] = "پاک کردن فیلتر",
        ["Filter.Showing"] = "نمایش",
        ["Group.Reasons"] = "دلایل تطابق",

        ["Msg.ImportDone"] = "‏{0} گروه وارد شد.",

        ["Ctx.Open"] = "باز کردن فایل",
        ["Ctx.OpenLocation"] = "باز کردن محل فایل",
        ["Ctx.CopyPath"] = "کپی مسیر کامل",
        ["Ctx.CopyFolder"] = "کپی مسیر پوشه",
        ["Ctx.SelectRedundant"] = "انتخاب نسخه‌های اضافی این گروه",
        ["Ctx.ClearGroup"] = "پاک کردن انتخاب این گروه",

        ["Keep.Rule"] = "نگه‌داشتن بر اساس",
        ["Keep.Newest"] = "جدیدترین",
        ["Keep.Oldest"] = "قدیمی‌ترین",
        ["Keep.Largest"] = "بزرگ‌ترین",
        ["Keep.Smallest"] = "کوچک‌ترین",
        ["Keep.ShortestPath"] = "کوتاه‌ترین مسیر",
        ["Keep.CleanestName"] = "تمیزترین نام",

        ["Results.Header"] = "نتایج",
        ["Results.NoResults"] = "هنوز پویشی انجام نشده است",
        ["Results.NoDuplicates"] = "هیچ فایل تکراری‌ای پیدا نشد 🎉",
        ["Results.Group"] = "گروه",
        ["Results.FilesScanned"] = "فایل‌های بررسی‌شده",
        ["Results.Groups"] = "گروه‌های تکراری",
        ["Results.RedundantFiles"] = "فایل‌های اضافی",
        ["Results.Reclaimable"] = "فضای قابل آزادسازی",
        ["Results.Elapsed"] = "زمان",
        ["Results.Warnings"] = "هشدارها",
        ["Results.Selected"] = "انتخاب‌شده",

        ["Grid.Keep"] = "نگه‌داری",
        ["Grid.File"] = "نام فایل",
        ["Grid.Folder"] = "پوشه",
        ["Grid.Size"] = "اندازه",
        ["Grid.Modified"] = "آخرین تغییر",

        ["Status.Idle"] = "آماده",
        ["Status.Enumerating"] = "در حال فهرست‌برداری فایل‌ها…",
        ["Status.QuickScan"] = "غربال سریع (پیش‌بررسی)…",
        ["Status.HashingContent"] = "در حال محاسبه هش کامل…",
        ["Status.MatchingNames"] = "در حال تطبیق نام‌ها…",
        ["Status.HashingPerceptual"] = "در حال تحلیل تصاویر…",
        ["Status.SamplingVideo"] = "در حال نمونه‌برداری از ویدیوها…",
        ["Status.Finalizing"] = "در حال جمع‌بندی…",
        ["Status.Completed"] = "پویش کامل شد",
        ["Status.Cancelled"] = "پویش لغو شد",
        ["Status.Faulted"] = "خطا در پویش",

        ["Msg.NeedFolder"] = "لطفاً حداقل یک پوشه اضافه کنید.",
        ["Msg.NeedMethod"] = "لطفاً حداقل یک روش تشخیص را انتخاب کنید.",
        ["Msg.NothingSelected"] = "هیچ فایلی انتخاب نشده است.",
        ["Msg.ConfirmRecycle"] = "‏{0} فایل به سطل بازیافت منتقل شود؟",
        ["Msg.ConfirmDelete"] = "‏{0} فایل برای همیشه حذف شود؟ این عمل قابل بازگشت نیست!",
        ["Msg.ActionDone"] = "‏{0} فایل پردازش شد، {1} آزاد شد.",
        ["Msg.ActionErrors"] = "‏{0} فایل با خطا مواجه شد.",
        ["Msg.ExportDone"] = "گزارش ذخیره شد.",

        ["Common.Ok"] = "تأیید",
        ["Common.Cancel"] = "انصراف",
        ["Common.Yes"] = "بله",
        ["Common.No"] = "خیر",
        ["Common.Confirm"] = "تأیید عملیات",
        ["Common.Warning"] = "هشدار",
    };

    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["App.Title"] = "Duplicate Finder Pro",
        ["App.Subtitle"] = "Find duplicate files by content, name and visual similarity",

        ["Menu.Language"] = "Language",
        ["Menu.Theme"] = "Theme",
        ["Theme.Light"] = "Light",
        ["Theme.Dark"] = "Dark",
        ["Lang.Persian"] = "فارسی",
        ["Lang.English"] = "English",

        ["Config.Header"] = "Scan Settings",
        ["Config.Folders"] = "Folders",
        ["Config.AddFolder"] = "Add folder",
        ["Config.RemoveFolder"] = "Remove",
        ["Config.DropHint"] = "Drop folders here or click “Add folder”",
        ["Config.Methods"] = "Detection methods",
        ["Config.Filters"] = "Filters",
        ["Config.Advanced"] = "Advanced",
        ["Config.Recursive"] = "Search sub-folders",
        ["Config.IncludeHidden"] = "Include hidden/system files",
        ["Config.MinSize"] = "Minimum size (KB)",
        ["Config.MaxSize"] = "Maximum size (KB, 0 = unlimited)",
        ["Config.IncludeExt"] = "Only these extensions (comma separated)",
        ["Config.ExcludeExt"] = "Ignore extensions (comma separated)",
        ["Config.FileTypes"] = "File types to scan",
        ["Config.FileTypesHint"] = "Empty = all files. Pick some and only those kinds are searched (never executables/system files).",
        ["Cat.Images"] = "Images",
        ["Cat.Videos"] = "Videos",
        ["Cat.Audio"] = "Audio",
        ["Cat.Documents"] = "Documents",
        ["Cat.Archives"] = "Archives",
        ["Config.NameThreshold"] = "Name similarity threshold",
        ["Config.PerceptualThreshold"] = "Image similarity threshold (0–64)",
        ["Config.VideoSamples"] = "Sample frames per video",
        ["Config.VideoIntroSkip"] = "Skip from start (%)",
        ["Config.VideoOutroSkip"] = "Skip from end (%)",
        ["Config.Gentle"] = "Gentle mode (lower system load)",
        ["Config.Ffmpeg"] = "ffmpeg path (optional)",

        ["Config.ResourceUsage"] = "Resource usage",
        ["Res.Maximum"] = "Maximum",
        ["Res.Maximum.Desc"] = "Use all cores — fastest, but the machine gets busy",
        ["Res.Balanced"] = "Balanced",
        ["Res.Balanced.Desc"] = "Half the cores — a smooth, responsive default",
        ["Res.Light"] = "Light",
        ["Res.Light.Desc"] = "Single-threaded, low priority — gentle on the disk (best for HDDs)",

        ["Config.ExcludedFolders"] = "Excluded folders",
        ["Config.AddExcluded"] = "Add folder to exclude",
        ["Config.ExcludedHint"] = "These sub-folders are skipped during the scan",

        ["Scan.Title"] = "Scanning…",
        ["Scan.FilesFound"] = "Files found",
        ["Scan.Processed"] = "Processed",
        ["Scan.Duplicates"] = "Duplicates found",
        ["Scan.Elapsed"] = "Elapsed",
        ["Scan.Location"] = "Current location",
        ["Scan.Phase"] = "Phase",
        ["Scan.Remaining"] = "Time remaining",
        ["Scan.CurrentFile"] = "File being checked",
        ["Scan.FilesUnit"] = "files",
        ["Scan.ReadingFile"] = "Reading this file",

        ["Explain.Enumerating"] = "Listing every file in the selected folders and sub-folders.",
        ["Explain.QuickScan"] = "Quick pre-filter: reads only a small sample of each same-size file so most are ruled out without a full read.",
        ["Explain.HashingContent"] = "Reading candidate files fully and computing a unique signature (SHA-256) to confirm byte-for-byte duplicates. This is the heaviest step.",
        ["Explain.MatchingNames"] = "Comparing file names to find renamed copies.",
        ["Explain.HashingPerceptual"] = "Fingerprinting each image to find look-alike photos.",
        ["Explain.SamplingVideo"] = "Sampling frames from each video to match the same movie.",
        ["Explain.AnalyzingPhotos"] = "Checking each photo for blur, darkness and screenshots.",
        ["Explain.Finalizing"] = "Grouping the results.",

        ["Adv.NameSection"] = "File-name matching",
        ["Adv.ImageSection"] = "Images",
        ["Adv.VideoSection"] = "Videos",
        ["Adv.NameDesc"] = "Names are normalized and compared by edit distance. Higher threshold = stricter.",
        ["Adv.ImageDesc"] = "Compares perceptual fingerprints (dHash) of images; survives resize, recompression and format changes. Lower number = stricter.",
        ["Adv.VideoDesc"] = "Samples frames from across the whole runtime (not just the start) so films with similar intros aren't merged. More samples = more accurate but slower.",
        ["Adv.GentleDesc"] = "Runs media analysis at low priority with limited concurrency so the machine stays responsive.",
        ["Adv.EnableHint"] = "Tick this method in “Detection methods” to enable these options",
        ["Adv.NamePro"] = "Pro: fast, and catches renamed copies.",
        ["Adv.NameCon"] = "Con: may group different files that just share a similar name.",
        ["Adv.ImagePro"] = "Pro: detects the same picture in a different format, size or quality.",
        ["Adv.ImageCon"] = "Con: a bit slower; a loose threshold can match merely-similar images.",
        ["Adv.VideoPro"] = "Pro: finds the same movie under a different name, quality or format.",
        ["Adv.VideoCon"] = "Con: requires ffmpeg and is CPU/time heavy.",
        ["Adv.VideoSampling"] = "Samples random points across the whole film (start, middle and end); the spots differ each scan but stay identical for copies of the same film.",

        ["Action.DownloadFfmpeg"] = "Download ffmpeg automatically",
        ["Ffmpeg.Ready"] = "ffmpeg is ready ✓",
        ["Ffmpeg.Missing"] = "ffmpeg not found — required for video matching",
        ["Ffmpeg.Downloading"] = "Downloading ffmpeg…",
        ["Ffmpeg.Done"] = "ffmpeg installed successfully ✓",
        ["Ffmpeg.Failed"] = "ffmpeg download failed",
        ["Ffmpeg.Redownload"] = "Re-download",

        ["Status.AnalyzingPhotos"] = "Analyzing photo quality…",

        ["Tab.Duplicates"] = "Duplicates",
        ["Tab.PhotoCleanup"] = "Photo cleanup",
        ["Tab.Statistics"] = "Statistics",

        ["Method.PhotoQuality"] = "Photo quality analysis (gallery cleanup)",
        ["Method.PhotoQuality.Desc"] = "Find blurry, dark, low-quality and screenshot photos",

        ["Photo.Blurry"] = "Blurry",
        ["Photo.Dark"] = "Dark",
        ["Photo.Overexposed"] = "Overexposed",
        ["Photo.LowResolution"] = "Low-res",
        ["Photo.Screenshot"] = "Screenshot",
        ["Photo.Good"] = "Good",
        ["Photo.ShowOnlyFlagged"] = "Only flagged photos",
        ["Photo.SelectFlagged"] = "Select all flagged",
        ["Photo.NoPhotos"] = "No analysis yet — tick “Photo quality analysis” and scan",
        ["Photo.Analyzed"] = "photos analyzed",
        ["Photo.Flagged"] = "flagged",

        ["Grid.Preview"] = "Preview",
        ["Grid.Score"] = "Score",
        ["Grid.Issues"] = "Issues",
        ["Grid.Resolution"] = "Resolution",

        ["Stat.Type.Images"] = "Images",
        ["Stat.Type.Videos"] = "Videos",
        ["Stat.Type.Other"] = "Other",
        ["Stat.ByType"] = "Size by file type",
        ["Stat.ByMethod"] = "Reclaimable space by method",
        ["Stat.PhotoQuality"] = "Photo quality breakdown",
        ["Stat.TopGroups"] = "Largest duplicate groups",
        ["Stat.Overview"] = "Overview",
        ["Stat.BytesScanned"] = "Data scanned",
        ["Stat.NoStats"] = "Statistics appear here after a scan",

        ["Adv.PhotoSection"] = "Photo quality",
        ["Adv.PhotoDesc"] = "Measures sharpness (Laplacian variance), brightness and size to flag blurry / dark / screenshot photos.",
        ["Adv.PhotoPro"] = "Pro: great for quickly cleaning up a phone gallery.",
        ["Adv.PhotoCon"] = "Con: it's a subjective judgement — always review before deleting.",
        ["Config.BlurSensitivity"] = "Blur sensitivity (higher = stricter)",

        ["Method.ExactContent"] = "Exact content (hash)",
        ["Method.ExactContent.Desc"] = "Byte-for-byte identical files, even with different names",
        ["Method.NameSimilarity"] = "File name similarity",
        ["Method.NameSimilarity.Desc"] = "Similar names like Movie and Movie (1)",
        ["Method.PerceptualImage"] = "Look-alike images",
        ["Method.PerceptualImage.Desc"] = "Same picture in a different format or quality",
        ["Method.PerceptualVideo"] = "Look-alike videos (ffmpeg)",
        ["Method.PerceptualVideo.Desc"] = "The same movie under a different name/quality",

        ["Action.Scan"] = "Start scan",
        ["Action.Cancel"] = "Cancel",
        ["Action.Export"] = "Export report",
        ["Action.ExportCsv"] = "Export CSV",
        ["Action.ExportJson"] = "Export JSON",
        ["Action.Recycle"] = "Move to Recycle Bin",
        ["Action.DeletePermanently"] = "Delete permanently",
        ["Action.MoveTo"] = "Move to folder…",
        ["Action.OpenFolder"] = "Open file location",
        ["Action.SelectByRule"] = "Auto-select",
        ["Action.ClearSelection"] = "Clear selection",
        ["Action.ExpandAll"] = "Expand all",
        ["Action.CollapseAll"] = "Collapse all",
        ["Action.Search"] = "Search results…",
        ["Action.Import"] = "Import results",
        ["Action.SaveSession"] = "Save results",

        ["Filter.Title"] = "Filter & query",
        ["Filter.Reasons"] = "By match reason",
        ["Filter.MatchAll"] = "Must match all selected",
        ["Filter.MinSimilarity"] = "Min similarity",
        ["Filter.MinCount"] = "Min files per group",
        ["Filter.Reset"] = "Clear filter",
        ["Filter.Showing"] = "Showing",
        ["Group.Reasons"] = "Match reasons",

        ["Msg.ImportDone"] = "{0} groups imported.",

        ["Ctx.Open"] = "Open file",
        ["Ctx.OpenLocation"] = "Open file location",
        ["Ctx.CopyPath"] = "Copy full path",
        ["Ctx.CopyFolder"] = "Copy folder path",
        ["Ctx.SelectRedundant"] = "Select redundant copies in this group",
        ["Ctx.ClearGroup"] = "Clear this group's selection",

        ["Keep.Rule"] = "Keep by",
        ["Keep.Newest"] = "Newest",
        ["Keep.Oldest"] = "Oldest",
        ["Keep.Largest"] = "Largest",
        ["Keep.Smallest"] = "Smallest",
        ["Keep.ShortestPath"] = "Shortest path",
        ["Keep.CleanestName"] = "Cleanest name",

        ["Results.Header"] = "Results",
        ["Results.NoResults"] = "No scan has been run yet",
        ["Results.NoDuplicates"] = "No duplicate files found 🎉",
        ["Results.Group"] = "Group",
        ["Results.FilesScanned"] = "Files scanned",
        ["Results.Groups"] = "Duplicate groups",
        ["Results.RedundantFiles"] = "Redundant files",
        ["Results.Reclaimable"] = "Reclaimable space",
        ["Results.Elapsed"] = "Elapsed",
        ["Results.Warnings"] = "Warnings",
        ["Results.Selected"] = "Selected",

        ["Grid.Keep"] = "Keep",
        ["Grid.File"] = "File name",
        ["Grid.Folder"] = "Folder",
        ["Grid.Size"] = "Size",
        ["Grid.Modified"] = "Last modified",

        ["Status.Idle"] = "Ready",
        ["Status.Enumerating"] = "Enumerating files…",
        ["Status.QuickScan"] = "Quick pre-scan…",
        ["Status.HashingContent"] = "Full content hashing…",
        ["Status.MatchingNames"] = "Matching names…",
        ["Status.HashingPerceptual"] = "Analyzing images…",
        ["Status.SamplingVideo"] = "Sampling videos…",
        ["Status.Finalizing"] = "Finalizing…",
        ["Status.Completed"] = "Scan complete",
        ["Status.Cancelled"] = "Scan cancelled",
        ["Status.Faulted"] = "Scan failed",

        ["Msg.NeedFolder"] = "Please add at least one folder.",
        ["Msg.NeedMethod"] = "Please select at least one detection method.",
        ["Msg.NothingSelected"] = "No files are selected.",
        ["Msg.ConfirmRecycle"] = "Move {0} file(s) to the Recycle Bin?",
        ["Msg.ConfirmDelete"] = "Permanently delete {0} file(s)? This cannot be undone!",
        ["Msg.ActionDone"] = "Processed {0} file(s), freed {1}.",
        ["Msg.ActionErrors"] = "{0} file(s) failed.",
        ["Msg.ExportDone"] = "Report saved.",

        ["Common.Ok"] = "OK",
        ["Common.Cancel"] = "Cancel",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Confirm"] = "Confirm action",
        ["Common.Warning"] = "Warning",
    };
}
